[package]
cairo-version = "2.12.2"
name = "starter"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[dependencies]
starknet = "2.12.2"
dojo = "1.7.2"

[dev-dependencies]
cairo_test = "2.12.2"
dojo_cairo_test = "1.7.2"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]
